/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ashwin.java.mathutils;

public class Arithmetics {
    public static double add(double a, double b) {
        return a + b;
    }
}
